# Generated by Django 5.0.6 on 2024-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('profesor', models.CharField(max_length=100, verbose_name='Profesor')),
                ('cupo', models.SmallIntegerField(verbose_name='Cupo')),
                ('horarios', models.CharField(max_length=100, verbose_name='Horario')),
            ],
        ),
    ]
