# Generated by Django 5.0.6 on 2024-06-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_clase_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='horarios',
            field=models.CharField(choices=[('MAÑANA', 'mañana'), ('TARDE', 'tarde')], default='TARDE', max_length=10),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.profesor'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
    ]
