# Generated by Django 5.0.6 on 2024-06-14 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_inscripcion_options_alter_profesor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.profesor'),
        ),
    ]
